### ISSUE TITLE
bug: unable to start my wrappid native app

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/native-mobile#22]
**Describe the bug**
My app is not starting with commnad 'wr start mobile' and I am getting errors:  ERROR  Warning: Failed prop type: Invalid props.style key `borderStyle` supplied to `Image`.
Bad object: {
  "width": "25%",
  "height": "25%",
  "borderWidth": 1,
  "borderColor": "black",
  "borderStyle": "solid"
}
Enviroment: Dev
![Screenshot (4)](https://github.com/wrappid/native-mobile/assets/88425657/780b1ea7-c4db-4535-a2ee-8ced7738d4dc)

**To Reproduce**
1. Go to 'start wrappid mobile app'

**Expected behavior**

**Stack Trace**
The stack trace of the bug if any.

**Screenshots**
![Screenshot (2)](https://github.com/wrappid/native-mobile/assets/88425657/a4a36b0a-c9c5-43b9-8183-9111526feb3c)
![Screenshot (3)](https://github.com/wrappid/native-mobile/assets/88425657/b5aa0aff-8669-4f4c-86f3-5a368f618565)

**Desktop (please complete the following information):**
 - windows
 - Version [e.g. 10]

**Smartphone (please complete the following information):**
 - Device: [e.g. Android Virtual Machine]

**Additional context**

**Comment by techoneel** [comment]
this issue got resolved
