### ISSUE TITLE
refactor: linting implementation

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/native-mobile#33]
## Description
Using eslint need to implement linting.

**Comment by anantakumarghosh** [comment]
eslint file already added. Another issue will be opened for any changes in lint config.

**Comment by Edithmark42** [comment]
Reopening this issue as there is a requirement for resolving React import issue in the package as the import got removed in the previous linting fix in #46 issue.

**Comment by Swrnv-qc** [comment]
@Edithmark42 Fixed the import issues.
