### ISSUE TITLE
bug: pr guardrails linting deleted file

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/native-mobile#43]
**Describe the bug**
On creating Pull Request, es-lint is trying to lint deleted files and failing.

**To Reproduce**

**Expected behavior**

**Stack Trace**
The stack trace of the bug if any.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techoneel** [comment]
This issue got resolved but linting problems are still there.
