### ISSUE TITLE
enhancement: delivery oriented fix

### ISSUE THREAD

**Issue by sumanta-m** [wrappid/native-mobile#62]
- [x] native-mobile package missing a required package @react-native-community/netinfo. Mentioned package is missing from the package.json which resides within the package folder.

**Comment by anantakumarghosh** [comment]
@react-native-community/netinfo already exists in package/package.json since native-mobile [v0.0.237](https://github.com/wrappid/native-mobile/releases/tag/v0.0.237)

**Comment by anantakumarghosh** [comment]
> @react-native-community/netinfo already exists in package/package.json since native-mobile [v0.0.237](https://github.com/wrappid/native-mobile/releases/tag/v0.0.237)

closing.
